services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: revofashion_api
    ports:
      - "5001:5000"
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      PORT: 5000
      SECRET_KEY: docker_dev_secret_key
      JWT_SECRET_KEY: docker_dev_jwt_secret_key
      DATABASE_URL: postgresql://postgres:postgres@db:5432/revoshop_db
      CORS_ALLOWED_ORIGINS: "*"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: revofashion_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: revoshop_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d revoshop_db"]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
