"""add fashion fields to products and order_items

Revision ID: 4a6a7141b8ab
Revises: d2ba64539b06
Create Date: 2026-08-17 20:55:24.395688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a6a7141b8ab'
down_revision = 'd2ba64539b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('material', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sku', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['sku'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('sku')
        batch_op.drop_column('gender')
        batch_op.drop_column('material')
        batch_op.drop_column('color')
        batch_op.drop_column('size')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('color')
        batch_op.drop_column('size')

    # ### end Alembic commands ###
