"""adjust_fashion_products_orders_roles

Revision ID: b102e24f5184
Revises: b849058b3a5a
Create Date: 2026-08-19 11:39:36.376064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b102e24f5184'
down_revision = 'b849058b3a5a'
branch_labels = None
depends_on = None


def upgrade():
    # Backfill existing NULLs before altering to NOT NULL
    op.execute("UPDATE order_items SET size = 'Free Size' WHERE size IS NULL")
    op.execute("UPDATE order_items SET color = 'Default' WHERE color IS NULL")
    op.execute("UPDATE orders SET shipping_address = 'Address not specified' WHERE shipping_address IS NULL")
    op.execute("UPDATE orders SET recipient_name = 'Customer' WHERE recipient_name IS NULL")
    op.execute("UPDATE orders SET recipient_phone = '0000000000' WHERE recipient_phone IS NULL")
    op.execute("UPDATE products SET size = 'Free Size' WHERE size IS NULL")
    op.execute("UPDATE products SET color = 'Default' WHERE color IS NULL")
    op.execute("UPDATE products SET gender = 'Unisex' WHERE gender IS NULL")
    op.execute("UPDATE products SET sku = 'UQ-' || substring(md5(random()::text), 1, 8) WHERE sku IS NULL")
    op.execute("UPDATE users SET role = 'customer' WHERE role = 'seller' OR role = 'user'")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('shipping_address',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('recipient_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('recipient_phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('sku',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('sku',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('size',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('recipient_phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('recipient_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('shipping_address',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('size',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
