"""add shipping fields to orders

Revision ID: b849058b3a5a
Revises: 4a6a7141b8ab
Create Date: 2026-08-19 10:36:47.379813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b849058b3a5a'
down_revision = '4a6a7141b8ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recipient_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('recipient_phone', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('recipient_phone')
        batch_op.drop_column('recipient_name')
        batch_op.drop_column('shipping_address')

    # ### end Alembic commands ###
