"""add tracking_number and cancellation_reason to orders

Revision ID: f885a2130cb6
Revises: b102e24f5184
Create Date: 2026-08-19 14:20:25.100457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f885a2130cb6'
down_revision = 'b102e24f5184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('tracking_number')

    # ### end Alembic commands ###
